### PR TITLE
040 add login system

### PR DESCRIPTION
**Pull request by ntotten-kainos**
Frontend changes required to enable a login/authentication system.

- [x] Build & Linter passing on Actions
- [x] Tests passing locally

### CODE REVIEW

**Review by mark-mcilroykainos — APPROVED** [review]
LGTM great work Nathan

**Comment by ntotten-kainos** [comment]
Ready for review

**Review by JamieMcConnellKainos — APPROVED** [review]
looks good

**Review by ashnabraham — APPROVED** [review]
looks great !!

**Review by boydstepkainos — APPROVED** [review]

**Pull request merged**
